theme: jekyll-theme-slate
title: Stacie McKee
subtitle: Technical Writing Portfolio
paragraph: I share excerpted samples due to non-disclosure restrictions.
<img style="float: left;" src="images/cptc.jpg">
